version: "3.9"
services:
    db:
        build: ./db/
        ports:
            - 5432:5432
        volumes:
            - temp_data:/var/lib/postgresql/data
    app:
        build: ./app/
        depends_on:
            - db
volumes:
    temp_data: