version: "3.9"
services:
    db:
        build: ./db/
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: testdb
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            retries: 5
        restart: always        
    app:
        build: ./app/
        depends_on:
            db:
                condition: service_healthy
        links:
            - db
